### ISSUE TITLE
FormBuilderTypeAhead get typed value if it's not one of the suggestions

### ISSUE THREAD

**Issue by nrallakis** [flutter-form-builder-ecosystem/form_builder_extra_fields#24] opened 2022-08-03 15:09 UTC
## Environment 
Windows

**Package version: 7.5.0**

## Describe your question
Hi, how can I get the typed value of a FormBuilderTypeAhead if the value is not one of the selections?
I want to use the typeahead only to suggest options, not to force an option.
If I type something not available in the suggestions and save the form, the map returns a null instead of the typed value.
Is there any workaround?

**Comment by deandreamatias** [comment] 2022-08-03 17:23
@nrallakis I transferred this issue to form_builder_extra_fields because FormBuilderTypeAhead is from here

Maybe you can implement some logic here to show the query + your suggestions

```dart
suggestionsCallback: (query) {
  if (query.isNotEmpty) {
    var lowercaseQuery = query.toLowerCase();
    return allCountries.where((country) {
      return country.toLowerCase().contains(lowercaseQuery);
    }).toList(growable: false)
      ..sort((a, b) => a
          .toLowerCase()
          .indexOf(lowercaseQuery)
          .compareTo(
              b.toLowerCase().indexOf(lowercaseQuery)));
  } else {
    return allCountries;
  }
},
```

**Comment by deandreamatias** [comment] 2022-08-03 20:13
Ok, but I think that this is the expected behavior (from a UX view)

**Comment by nrallakis** [comment] 2022-08-03 20:29
Yes, I think its fine, as long as you don't press tab or click outside (windows).
Thanks again!

**Closed** 2022-08-03 20:42 UTC
Labels: question
